paths:
  raw_orders: "dbfs:/Volumes/workspace/default/files/orders.csv"
  bronze_orders: "dbfs:/Volumes/workspace/default/files/bronze/orders"
  silver_orders: "dbfs:/Volumes/workspace/default/files/silver/orders"
  gold_sales: "dbfs:/Volumes/workspace/default/files/gold/product_sales"


spark:
  app_name: "DatabricksOrdersPipeline"
